services:
  db:
    image: postgres:15
    container_name: emr-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - emr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10



  adminer:
    image: adminer:4
    container_name: emr-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - emr-network
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emr-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - emr-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emr-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - emr-network
    depends_on:
      - backend

networks:
  emr-network:
    driver: bridge
    name: emr-network

volumes:
  pgdata:
